name: avl-use-cases
channels:
  - conda-forge
dependencies:
  - atmosphere-virtual-lab
  - branca
  - cartopy
  - cmcrameri
  - folium
  - geopandas
  - matplotlib
  - netcdf4
  - nodejs
  - sentinelsat
  - vtk>=9.1=osmesa*
  - jupyter_server<2
