name: avl
channels:
  - conda-forge
dependencies:
  - atmosphere-virtual-lab
  - branca
  - cartopy
  - cmcrameri
  - folium
  - geopandas
  - matplotlib
  - netcdf4
  - nodejs
  - sentinelsat
  - jupyter_server<2
