name: avl
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - cmcrameri
  - coda
  - harp
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib
  - nodejs
  - plotly
  - requests
  - sentinelsat
